2025-04-29 08:30:33.231162 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:30:33.238708 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:30:38.425828 No username stored in session but dashboard was accessed @ip=127.0.0.1
2025-04-29 08:30:38.426154 Forbidden access @ip=<Request 'http://127.0.0.1:5000/dashboard' [GET]>: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1314, in __inner
    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 58, in dashboard
    abort(403)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 372, in forbidden
    return render_template('error.html', error=403), 403
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:30:38.432578 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:30:38.535189 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:30:38.538946 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:15.600241 No username stored in session but dashboard was accessed @ip=127.0.0.1
2025-04-29 08:31:15.602218 Forbidden access @ip=<Request 'http://127.0.0.1:5000/dashboard' [GET]>: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1314, in __inner
    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 58, in dashboard
    abort(403)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 372, in forbidden
    return render_template('error.html', error=403), 403
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:15.605896 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:15.656054 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:15.658424 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:16.803001 No username stored in session but dashboard was accessed @ip=127.0.0.1
2025-04-29 08:31:16.803264 Forbidden access @ip=<Request 'http://127.0.0.1:5000/dashboard' [GET]>: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1314, in __inner
    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 58, in dashboard
    abort(403)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 372, in forbidden
    return render_template('error.html', error=403), 403
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:16.805861 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:16.845298 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:16.847406 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:17.299509 Exception @ip=127.0.0.1: 429 Too Many Requests: 1 per 1 second
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1310, in __inner
    self.limiter._check_request_limit(
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1172, in _check_request_limit
    raise e
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask_limiter/extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1 per 1 second

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 352, in handle_exception
    return render_template('error.html', error='')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:17.302092 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:17.362092 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:17.364704 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:31:20.562849 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:31:20.565125 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:23.840049 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:23.843676 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:24.846631 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:24.848775 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:25.633304 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:25.635302 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:38.736081 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:38.739771 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:39.682068 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:39.684038 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:39.919314 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:39.921498 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:32:41.105667 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:32:41.107159 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:33:41.630977 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:33:41.644865 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:34:03.350698 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:34:03.353569 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:35:40.485126 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:35:40.489067 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:35:41.948064 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:35:41.950254 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:37:39.911434 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:37:39.915046 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:37:40.794271 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:37:40.796978 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:50.657981 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:50.672706 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:51.617213 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:51.619109 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:51.805178 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:51.807497 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:51.980725 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:51.983379 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:52.135653 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:52.137705 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:54.484452 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:54.487559 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:38:57.985538 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:38:57.991465 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:39:57.458494 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:39:57.478188 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:39:58.598640 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:39:58.600956 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:39:59.496289 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/main.py", line 377, in page_not_found
    return render_template('error.html', error=404), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/angusallen/Documents/GitHub/Assessment_Task3/env/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
2025-04-29 08:39:59.499177 Internal Server Error @ip=127.0.0.1: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-04-29 08:41:10.608487 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 08:41:58.733476 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 08:41:59.914930 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:10:56.235997 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:10:56.239023 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:10:56.365063 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:19.632409 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:19.634791 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:19.710406 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:20.873018 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:20.873303 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:20.933033 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:35.503176 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:35.521356 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:35.561298 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:36.464096 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:36.480712 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:36.510037 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.115226 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.130036 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.163075 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.412489 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.414295 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:37.467302 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:52.588611 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:52.604907 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:11:52.646785 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:12:00.807376 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:12:00.823774 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:12:00.861399 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.124438 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.127312 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.219542 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.783616 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.783880 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:45.832581 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.078064 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.082873 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.139738 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.476455 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.479286 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:46.526182 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:55.719329 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:55.720499 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:55.762281 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:56.857662 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:56.861504 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:15:56.913774 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:21.348195 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:21.391429 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:46.226762 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:46.273128 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:47.401968 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:16:47.471189 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:11.602929 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:11.669230 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.429839 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.481833 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.747391 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.815460 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.923280 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:19:12.998961 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:08.989829 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:09.071256 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:09.748480 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:09.789653 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:09.894121 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:09.943379 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:10.040720 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:10.187089 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:10.239727 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:36.088092 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:36.165362 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:36.757380 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:36.815677 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:36.974583 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:37.006536 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:37.107808 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:37.165018 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:37.269275 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:37.327750 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:47.616101 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:20:47.744294 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:32.621978 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:32.693842 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:33.316451 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:33.366064 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:33.629063 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:21:33.687356 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:22:45.409410 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:22:45.487199 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:23:30.868329 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:23:30.947317 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:24:38.032943 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:24:58.688452 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:24:58.724390 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:25:19.814889 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:25:19.899215 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:14.721431 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:14.762985 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:15.447389 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:15.497381 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:44.116816 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:27:44.187848 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:28:03.249703 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:28:03.279841 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:28:04.068521 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:30:08.828662 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:31:44.228026 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-29 11:32:50.638615 Page not found @ip=127.0.0.1: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
